/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailySpecial {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : string,
  'category' : string,
  'price' : string,
}
export interface _SERVICE {
  'addDailySpecial' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'addMenuItem' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    undefined
  >,
  'getDailySpecials' : ActorMethod<[], Array<DailySpecial>>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'removeDailySpecial' : ActorMethod<[bigint], undefined>,
  'removeMenuItem' : ActorMethod<[bigint], undefined>,
  'seedDefaultData' : ActorMethod<[], undefined>,
  'updateDailySpecial' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, string, string, string, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];